# Generated by Django 3.1.4 on 2022-02-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='email',
            field=models.EmailField(default='iiitnr@gmail.com', max_length=150),
            preserve_default=False,
        ),
    ]
