# Generated by Django 3.1.4 on 2022-02-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_familymembers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='initiation',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='NO', max_length=3),
            preserve_default=False,
        ),
    ]
