# Generated by Django 3.1.4 on 2022-02-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_familymembers_initiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='family_code',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
