# Generated by Django 3.1.4 on 2022-02-06 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0004_auto_20220206_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhead',
            name='family_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
