# Generated by Django 3.1.4 on 2022-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_familyhead_family_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhead',
            name='date_of_init',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyhead',
            name='ritwik',
            field=models.CharField(default='ritwik1', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymembers',
            name='date_of_init',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
